version: '3.5'

services:
  kwetter_database:
    image: microsoft/mssql-server-linux:2017-latest
    hostname: 'sqlserver'
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_DB: Kwetter
      MSSQL_USER: Kwetter
      MSSQL_PASSWORD: Mb21532153
      MSSQL_SA_PASSWORD: Mb21532153
      MSSQL_PID: Developer
    volumes:
      - /var/opt/mssql
      - ms-sqlserver-data:/var/opt/mssql
      - .:/usr/src/app
    ports:
      - 1433:1433
    working_dir: /usr/src/app
    command: sh -c ' chmod +x ./configure_db.sh; ./configure_db.sh & /opt/mssql/bin/sqlservr;'
    restart: on-failure

volumes:
  ms-sqlserver-data:
    driver: local